default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: recordly_development

test:
  <<: *default
  database: recordly_test

production:
  <<: *default
  database: recordly_production
  username: recordly
  password: <%= ENV['RECORDLY_DATABASE_PASSWORD'] %>
